version: '3.8'

services:
  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - load-balancing
    container_name: load-balancer
    ports:
      - 8080:8080

networks:
  load-balancing:
    name: load-balancing